[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name =  "rflow"
description = "A rectified flow implementation in Flax"
authors = [{name = "Simon Dirmeier", email = "simd23@pm.me"}]
readme = "README.md"
license = {file = "LICENSE"}
classifiers = [
    "Development Status :: 1 - Planning",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
requires-python = ">=3.11"
dependencies = [
    "flax>=0.8.5",
    "optax>=0.2.3",
    "ml_collections>=0.1.1",
    "jax>=0.4.31",
    "tensorflow-probability[jax]>=0.24.0",
]
dynamic = ["version"]

[dependency-groups]
dev = [
    "pre-commit",
    "ruff",
    "wandb>=0.21.1",
]
examples = [
    "matplotlib>=3.10.5",
    "tensorflow>=2.17.0",
    "tensorflow-datasets>=4.9.6",
    "wandb>=0.21.1",
]

[tool.setuptools]
packages = ["rflow"]

[tool.setuptools.dynamic]
version = {attr = "rflow.__init__.__version__"}

[tool.ruff]
indent-width = 2
line-length = 80

[tool.ruff.lint.pydocstyle]
convention= 'google'
